name       : protobuf-c
version    : 1.3.1
release    : 4
source     :
    - https://github.com/protobuf-c/protobuf-c/archive/v1.3.1.tar.gz : 5eeec797d7ff1d4b1e507925a1780fad5dd8dd11163203d8832e5a9f20a79b08
license    : BSD-2-Clause
component  : programming.library
summary    : Protocol Buffers implementation in C
description: |
    This is protobuf-c, a C implementation of the Google Protocol
    Buffers data serialization format. It includes libprotobuf-c, a pure C
    library that implements protobuf encoding and decoding, and protoc-c,
    a code generator that converts Protocol Buffer .proto files to C
    descriptor code, based on the original protoc. protobuf-c formerly
    included an RPC implementation; that code has been split out into the
    protobuf-c-rpc project.
builddeps  :
    - pkgconfig(protobuf)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
