name       : protobuf-c
version    : 1.4.1
release    : 9
source     :
    - https://github.com/protobuf-c/protobuf-c/releases/download/v1.4.1/protobuf-c-1.4.1.tar.gz : 4cc4facd508172f3e0a4d3a8736225d472418aee35b4ad053384b137b220339f
license    : BSD-2-Clause
component  : programming.library
summary    : Protocol Buffers implementation in C
description: |
    This is protobuf-c, a C implementation of the Google Protocol. Buffers data serialization format. It includes libprotobuf-c, a pure C library that implements protobuf encoding and decoding, and protoc-c,  a code generator that converts Protocol Buffer .proto files to C descriptor code, based on the original protoc. protobuf-c formerly included an RPC implementation; that code has been split out into the protobuf-c-rpc project.
builddeps  :
    - pkgconfig(protobuf)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
