name       : protobuf-c
version    : 1.3.0
release    : 2
source     :
    - https://github.com/protobuf-c/protobuf-c/releases/download/v1.3.0/protobuf-c-1.3.0.tar.gz : 5dc9ad7a9b889cf7c8ff6bf72215f1874a90260f60ad4f88acf21bb15d2752a1
license    : BSD-2-Clause
component  : programming.library
summary    : Protocol Buffers implementation in C
description: |
    This is protobuf-c, a C implementation of the Google Protocol
    Buffers data serialization format. It includes libprotobuf-c, a pure C
    library that implements protobuf encoding and decoding, and protoc-c,
    a code generator that converts Protocol Buffer .proto files to C
    descriptor code, based on the original protoc. protobuf-c formerly
    included an RPC implementation; that code has been split out into the
    protobuf-c-rpc project.
builddeps  :
    - pkgconfig(protobuf)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
